### ISSUE TITLE
Not working in colab.

### ISSUE THREAD

**Issue by darkon12** [camenduru/Unique3D-jupyter#1]
Hi,
I appreciate your work but the notebook is not working.
The last part of the log where I think is the error is as following:

Status Legend:
(OK):download completed.
env: TORCH_CUDA_ARCH_LIST="7.5, 8.6, 8.9"
env: PYOPENGL_PLATFORM="egl"
/content/Unique3D
2024-06-15 07:46:45.838186: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-15 07:46:45.838254: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-15 07:46:45.953068: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-15 07:46:48.308959: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading data from 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx' to file '/root/.u2net/u2net.onnx'.
100%|████████████████████████████████████████| 176M/176M [00:00<00:00, 880GB/s]
Warning! extra parameter in cli is not verified, may cause erros.
Loading pipeline components...: 100% 5/5 [00:00<00:00, 66.12it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Warning! extra parameter in cli is not verified, may cause erros.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
unet/config.json: 100% 871/871 [00:00<00:00, 5.38MB/s]
diffusion_pytorch_model.bin: 100% 3.44G/3.44G [00:17<00:00, 197MB/s]
vae/config.json: 100% 595/595 [00:00<00:00, 3.08MB/s]
diffusion_pytorch_model.bin: 100% 335M/335M [00:01<00:00, 277MB/s]
image_encoder/config.json: 100% 703/703 [00:00<00:00, 4.19MB/s]
pytorch_model.bin: 100% 1.22G/1.22G [01:17<00:00, 15.6MB/s]
(…)ature_extractor/preprocessor_config.json: 100% 518/518 [00:00<00:00, 3.69MB/s]
model_index.json: 100% 545/545 [00:00<00:00, 3.37MB/s]
Fetching 2 files:   0% 0/2 [00:00<?, ?it/s]
scheduler/scheduler_config.json: 100% 308/308 [00:00<00:00, 2.04MB/s]
Fetching 2 files: 100% 2/2 [00:00<00:00,  3.34it/s]
Loading pipeline components...: 100% 5/5 [00:00<00:00, 60.44it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2img.StableDiffusionImageCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
[F glutil.cpp:338] eglInitialize() failed

Best Regards

**Comment by darkon12** [comment]
Hi,
The gradio app is working now.
However trying to generate a model always gives an error.
This is the last part of the log:

Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://0a8d4d7a4e7b344abc.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
RGB image not RGBA! still remove bg!
  0% 0/30 [00:00<?, ?it/s]Warning! condition_latents is not None, but self_attn_ref is not enabled! This warning will only be raised once.
100% 30/30 [00:33<00:00,  1.12s/it]
100% 10/10 [00:13<00:00,  1.37s/it]
2024-06-18 09:44:13.861060909 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Concat node. Name:'/body/body.0/rdb1/Concat_3' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 201326592

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "/content/Unique3D/app/gradio_3dgen.py", line 21, in generate3dv2
    new_meshes = geo_reconstruct(rgb_pils, None, front_pil, do_refine=do_refine, predict_normal=True, expansion_weight=expansion_weight, init_type=init_type)
  File "/content/Unique3D/scripts/multiview_inference.py", line 70, in geo_reconstruct
    img_list = [front_pil] + run_sr_fast(refined_rgbs[1:])
  File "/content/Unique3D/scripts/refine_lr_to_sr.py", line 39, in run_sr_fast
    upsampler = RealESRGANer(
  File "/content/Unique3D/scripts/upsampler.py", line 51, in __init__
    self.model(sample_input)
  File "/content/Unique3D/scripts/load_onnx.py", line 40, in caller
    ort_outs = ort_session.run(None, ort_inputs)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Concat node. Name:'/body/body.0/rdb1/Concat_3' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 201326592

100% 30/30 [00:33<00:00,  1.12s/it]
100% 10/10 [00:13<00:00,  1.35s/it]
2024-06-18 09:46:06.336383031 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/body/body.0/rdb1/conv1/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 33554432

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "/content/Unique3D/app/gradio_3dgen.py", line 21, in generate3dv2
    new_meshes = geo_reconstruct(rgb_pils, None, front_pil, do_refine=do_refine, predict_normal=True, expansion_weight=expansion_weight, init_type=init_type)
  File "/content/Unique3D/scripts/multiview_inference.py", line 70, in geo_reconstruct
    img_list = [front_pil] + run_sr_fast(refined_rgbs[1:])
  File "/content/Unique3D/scripts/refine_lr_to_sr.py", line 39, in run_sr_fast
    upsampler = RealESRGANer(
  File "/content/Unique3D/scripts/upsampler.py", line 51, in __init__
    self.model(sample_input)
  File "/content/Unique3D/scripts/load_onnx.py", line 40, in caller
    ort_outs = ort_session.run(None, ort_inputs)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'/body/body.0/rdb1/conv1/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 33554432

RGB image not RGBA! still remove bg!
100% 30/30 [00:33<00:00,  1.11s/it]
100% 10/10 [00:13<00:00,  1.37s/it]
2024-06-18 09:47:35.101121213 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/body/body.0/rdb1/conv1/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 33554432

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "/content/Unique3D/app/gradio_3dgen.py", line 21, in generate3dv2
    new_meshes = geo_reconstruct(rgb_pils, None, front_pil, do_refine=do_refine, predict_normal=True, expansion_weight=expansion_weight, init_type=init_type)
  File "/content/Unique3D/scripts/multiview_inference.py", line 70, in geo_reconstruct
    img_list = [front_pil] + run_sr_fast(refined_rgbs[1:])
  File "/content/Unique3D/scripts/refine_lr_to_sr.py", line 39, in run_sr_fast
    upsampler = RealESRGANer(
  File "/content/Unique3D/scripts/upsampler.py", line 51, in __init__
    self.model(sample_input)
  File "/content/Unique3D/scripts/load_onnx.py", line 40, in caller
    ort_outs = ort_session.run(None, ort_inputs)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'/body/body.0/rdb1/conv1/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 33554432

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://0a8d4d7a4e7b344abc.gradio.live/

From my point of view I think that the error is on unique3d side.
